config/routes.rb
Rails.application.routes.draw do
  get 'checkout/index'
  post 'checkout/done'

  get 'menu/index'

  root to: 'home#index'
  get '/home', to: 'home#index'
  get '/contact_us', to: 'contact_us#index'
  get '/menu', to: 'menu#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :section
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :food_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  skip_before_filter :verify_authenticity_token
  def index
    @item = params[:item] ? FoodItem.find(params[:item]) : nil
    @total = @item.price.to_f + 10
  end

  def done
    @item = params[:item] ? FoodItem.find(params[:item]) : nil
    @total = @item.price.to_f + 10

    @name = params[:name]
    @phone_number = params[:phone]
    @address = params[:address]
  end
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
    @params = params
    @filters = ['Alphabetical', 'Price low to high', 'Price high to low']
    @sections = Section.all

    @food_items_filterd = FoodItem.all
    section_id_filtered = params[:section] ? Section.where(name: params[:section]).first.id : nil
    @food_items_filterd = params[:section] ? @food_items_filterd.where(section_id: section_id_filtered): @food_items_filterd
    @food_items_filterd = params[:filter] ?
      case params[:filter]
      when 'Alphabetical'
        @food_items_filterd.order(:name)
      when 'Price low to high'
        @food_items_filterd.order(price: :asc)
      when 'Price high to low'
        @food_items_filterd.order(price: :desc)
      else
        @food_items_filterd.all
      end
    : @food_items_filterd
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/views/checkout/done.html.erb
<div id="done">
  <div class="box fluid">
    <h1 class="title">
      Thank you
    </h1>
  </div>

  <div class="checkout_detail">
    <%= render partial: 'shared/checkout_item', locals: {item: @item, total: @total} %>

    <div class="checkout-info box" style="text-align: center">
      <span class="glyphicon glyphicon-ok" style="color: green; font-size: 3em"></span>
      <h4>It is a pleasure to serve you. We will deliver it right on time.</h4>
      <div class="container" style="width: 60%">
        <table class="table table-hover">
          <thead>
            <th style="width: 30%"></th>
            <th style="width: 70%"></th>
          </thead>
          <tbody>
            <tr>
              <td>Name</td>
              <td><%= @name %></td>
            </tr>

            <tr>
              <td>Phone number</td>
              <td><%= @phone_number %></td>
            </tr>

            <tr>
              <td>Address</td>
              <td><%= @address %></td>
            </tr>
          </tbody>


        </table>
      </div>

      <%= link_to 'Go to homepage', home_path, class: "btn btn-success" %>
    </div>
  </div>
</div>

app/views/checkout/index.html.erb
<div id="checkout">
  <!-- Title -->
  <div class="box fluid">
    <h1 class="title">
      Check out
    </h1>
  </div>

  <!-- Checkout section -->
  <div class="checkout-detail">
    <!-- Table -->
    <%= render partial: 'shared/checkout_item', locals: {item: @item, total: @total} %>

    <div class="checkout-info box">
      <h2 style="text-align: center">Billing info</h2>
      <div class="container" style="width: 60%; text-align: center">
        <form id="form-info" action="<%= url_for(action: 'done') %>" method="post">

          <input name="item" type="hidden" value="<%= @item.id %>">

          <div class="form-group row">
            <label for="name" class="col-md-3 col-sm-3 col-form-label">Name</label>
            <div class="col-md-9 col-sm-9 ">
              <input type="text" class="form-control" id="name" placeholder="Name" name="name">
            </div>
          </div>

          <div class="form-group row">
            <label for="phone" class="col-md-3 col-sm-3 col-form-label">Phone number</label>
            <div class="col-md-9 col-sm-9 ">
              <input type="text" class="form-control" id="phone" placeholder="Phone number" name="phone">
            </div>
          </div>

          <div class="form-group row">
            <label for="address" class="col-md-3 col-sm-3 col-form-label">Address</label>
            <div class="col-md-9 col-sm-9 ">
              <input type="text" class="form-control" id="address" placeholder="Address" name="address">
            </div>
          </div>


          <button class="btn btn-primary" type="submit" form="form-info" value="Submit">Submit</button>
        </form>
      </div>
    </div>

  </div> <!-- end checkout-detail -->

</div>

app/views/contact_us/index.html.erb
<%= provide :title, 'Contact Us' %>
<div class="row">
  <div class="box fluid" id="contact-us">
    <div class="col-md-6">
      <h1 style="text-align: center">
        Contact us
      </h1>
      <table class="table table-hover">

        <tr>
          <td>
            <span class="glyphicon glyphicon-home"></span>
          </td>
          <td>
            Tầng 8, tòa nhà Hanoi Creative City, 1 Lương Yên, Bạch Đằng, Hai Bà Trưng, Hà Nội 100000, Việt Nam
          </td>
        </tr>

        <tr>
          <td>
            <span class="glyphicon glyphicon-envelope"></span>
          </td>
          <td>
            +84 4 7308 0668
          </td>
        </tr>

      </table>
    </div>
    <div class="col-md-6">
      <div class="google-maps">
        <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.5020395970914!2d105.86102931514112!3d21.01258898600719!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135abf0be48433b%3A0xbdacc2cdc6079fe!2sUP+Coworking+Space!5e0!3m2!1svi!2s!4v1476378263921"
            width="600" height="450" frameborder="0" style="border:0" allowfullscreen>
        </iframe>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div id="home">
  <div class="box fluid">
    <h1 class="title">
      Up Restaurant
    </h1>
  </div>
  <div class="feature">
    <%= link_to 'Menu', menu_path, class: "btn btn-lg btn-primary" %>
    <%= link_to 'Contact Us', contact_us_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> - Up Restaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>
      $(document).on('turbolinks:load',function() {
          $('.tooltipster').tooltipster();
      });
    </script>

  </head>

  <body>
    <% if !current_page?(root_path) %>
      <div class="box fluid">
        <div class="nav-home">
          <%= link_to '', root_path, class: "glyphicon glyphicon-home pure" %>
        </div>
        <h1 class="title">
          <%= yield :title %>
        </h1>
      </div>
    <% end %>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/menu/index.html.erb
<%= provide :title, 'Menu' %>
<div id="menu">
  <div class="display-items">

    <div class="container-fluid">
      <!-- Section navigation -->
      <div class="row">
        <div class="col-md-2 col-sm-3">
          <div class="row">
            <div class="box side-menu">
              <ul class="nav nav-pills nav-stacked">
                <li class="nav-item">
                  <%= link_to 'All', menu_path(filter: params[:filter]), class: "nav-link #{"active" if !params[:section]}" %>
                </li>
                <% @sections.each do |section| %>
                  <li class="nav-item">
                    <%= link_to section.name, menu_path(section: section.name, filter: params[:filter]), class: "nav-link #{"active" if params[:section] == section.name}" %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>

          <!-- Filter navigation -->
          <div class="row">
            <div class="box side-menu">
              <ul class="nav nav-pills nav-stacked">
                <li class="nav-item">
                  <%= link_to 'Normal', menu_path(section: params[:section]), class: "nav-link #{"active" if !params[:filter]}" %>
                </li>
                <% @filters.each do |filter| %>
                  <li class="nav-item">
                    <%= link_to filter, menu_path(filter: filter, section: params[:section]), class: "nav-link #{"active" if params[:filter] == filter}" %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>

        <!-- Filtered Food Items -->
        <div class="col-md-10 col-sm-9">
          <div class="items box fluid">
            <!-- Table -->
            <table class="table table-hover">
              <thead>
                <tr>
                  <th style="width: 10%">No</th>
                  <th style="width: 20%">Name</th>
                  <th style="width: 60%">Description</th>
                  <th style="width: 5%%">Price</th>
                  <th style="width: 5%"></th>
                </tr>
              </thead>
              <!-- Table body -->
              <tbody>
                <% @food_items_filterd.each do |item| %>
                  <%= render partial: 'shared/item', locals: {item: item} %>
                <% end %>
              </tbody> <!-- end body -->
            </table> <!-- end table -->

          </div>

        </div>
    </div>

  </div>

</div>

app/views/shared/_checkout_item.html.erb
<div class="box checkout-items">
  <table class="table table-hover">

    <thead>
      <tr>
        <th style="width: 10%">No</th>
        <th style="width: 20%">Name</th>
        <th style="width: 60%">Description</th>
        <th style="width: 5%%">Price</th>
        <th style="width: 5%"></th>
      </tr>
    </thead>

    <!-- Table body -->
    <tbody>
      <%= render partial: 'shared/item', locals: {item: item} %>
    </tbody> <!-- end body -->

  </table> <!-- end table -->

  <hr>
  <div class="checkout-total">
    <h2>Total: <span class="price"><%= total %></span>$</h2>
  </div>

</div>

app/views/shared/_item.html.erb
<tr class="tooltipster" data-tooltip-content="#item-img-<%= item.id %>">
  <th scope="row"><%= item.id %></th>
  <td><strong><%= item.name %></strong></td>
  <td><%= item.description %></td>
  <td><%= item.price %>$</td>
  <td>
    <%= link_to '', checkout_index_path(item: item.id), class: "pure glyphicon glyphicon-shopping-cart" %>
  </td>
</tr>
<div class="tooltip_templates">
  <div id="item-img-<%= item.id %>">
    <img src="<%= item.img_url %>" />
    <h5><%= item.name %>: <%= item.price %>$</h5>
  </div>
</div>